#!/bin/sh

case "$1" in
  redesign)
    coffee -e "require('./server/db/design').importAll()"
    ;;
  reset)
    coffee -e "require('./server/db/design').destroyAndImportAll()"
    script/setup_search
    ;;
  *)
    echo $"Usage: script/db {redesign|reset}"
    exit 1
esac
