#!/bin/sh

curl -XDELETE http://localhost:9200/meals ; echo
curl -XPUT http://localhost:9200/meals -d '
  "settings": {
  }
' ; echo

curl -XDELETE http://localhost:9200/_river/meals ; echo
curl -XPUT http://localhost:9200/_river/meals/_meta -d '
{
  "type": "couchdb",
  "couchdb": {
    "host": "localhost",
    "port": 5984,
    "db": "meals",
    "filter": null
  },
  "index": {
    "index": "meals",
    "type": "meal"
  }
}' ; echo
